require_relative './domain/pull_request'
require_relative './domain/team'

require_relative './use_cases/fetch_pull_requests'
require_relative './use_cases/fetch_teams'
require_relative './gateways/pull_request'
require_relative './gateways/team'
require_relative './presenters/pull_requests_by_application'
require_relative './presenters/pull_requests_by_gem'
require_relative './presenters/pull_requests_by_team'
